### ISSUE TITLE
Ruby enum types are not documented

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#1313]
### What

We don't autogenerate proto/gRPC reference documentation for enum types. We should.

### Context

This was encountered in the form of missing docs for `TimeSeriesView` here: https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1473

**Comment by geigerj** [comment]
@landrito is there any update on this issue?

**Comment by landrito** [comment]
This was done with @eoogbe yard link fixes.

Heres where the fix is.
https://github.com/googleapis/toolkit/blob/master/src/main/resources/com/google/api/codegen/ruby/message.snip#L52

Heres an example of it in generated code.
https://github.com/googleapis/api-client-staging/pull/386/files#diff-b6bf314e9c12a857b36107e499f53e60R134
