### ISSUE TITLE
Sync with latest version of tools framework from github

### ISSUE THREAD

**Issue by guptasu** [googleapis/toolkit#144]
Currently the tool framework referenced by [toolkit](https://github.com/googleapis/toolkit) build.gradle is created using the Git-On-Borg toolsFx codebase. We want to reference the tools framework that is compiled using the code on github https://github.com/googleapis/api-compiler

**Comment by bjwatson** [comment]
FYI, @tbetbetbe. Sunny is referring to the fix-gapi-dev-build branch you created on March 28. It appears that toolkit only builds correctly with that version right now. I've tried it with the GoB master for gapi-tools-framework, and got a lot of compile errors. I have not tried it yet with the new Github tools-framework repo, but expect the same results.

**Comment by bjwatson** [comment]
We need to resolve compile errors with latest version on github, and depend on a built version of tools framework on Maven

**Comment by bjwatson** [comment]
I tried this today, and it seems to work fine. See https://github.com/googleapis/toolkit/pull/284, which is having errors for other reasons.

**Comment by garrettjonesgoogle** [comment]
The upgrade to protobuf 3.0.0-beta-3 has been done in https://github.com/googleapis/toolkit/commit/50fe9c9614c8dbe495913d3c7a0378210bc8d21c . The upgrade to protobuf-gradle-plugin:0.7.7 seems to be the cause of the problems in the present PR; I think we can defer that for later because I don't think we need any changes from protobuf-gradle-plugin. Lastly, the api-compiler dependency will be upgraded separately (once a non-snapshot version can be used).
