### ISSUE TITLE
Go: make the top-of-file editing message clearer.

### ISSUE THREAD

**Issue by jba** [googleapis/toolkit#187]
The current one suggests that some edits can be made. It even ends with "Happy editing!".

I'm particularly concerned about giving people false hope, since these files will live under handwritten, editable code.

So can we change everything from "EDITING INSTRUCTIONS" to the end of the comment to:

AUTO-GENERATED CODE. DO NOT EDIT.

**Comment by saicheems** [comment]
Agreed

**Comment by garrettjonesgoogle** [comment]
@jba : We used this wording because we intended the generated code of Veneer Toolkit to be editable (specifically for comments), and we have the three-way merge process to enable this. Do you want to make a rule that no generated Go files can be edited? Or is it specifically the generated Go files for APIs that will be wrapped?

**Comment by saicheems** [comment]
Is the three way merge process ready right now?

I think we're fine to remove the hand edit section for the short term at least, as we're neither expecting nor looking for contributions to the generated surface at the moment. Potentially receiving PRs against the still changing surface/docs could be a waste. Plus, APIs we're generating for are going to be hand-wrapped.

**Comment by garrettjonesgoogle** [comment]
This leaves me wondering if we should remove the notice from the generated Java files too.
