### ISSUE TITLE
Go: handle multi-service APIs better

### ISSUE THREAD

**Issue by jba** [googleapis/toolkit#188]
Currently an API that has multiple proto services (e.g. logging) generates three separate packages, with three separate clients.

The most immediate problem is that each client always creates its own gRPC connection. We should be able to reuse the same connection for all clients, since they are all talking to the same endpoint.

But I think we should generate one VKit package per API, rather than per service. The HTTP surface does not distinguish by service, so using the VKit would be less pleasant than using the API directly in this respect, which isn't desirable.

**Comment by broady** [comment]
> But I think we should generate one VKit package per API, rather than per service.

+1

**Comment by jba** [comment]
@saicheems 
@jmuk 
@vchudnov-g

**Comment by saicheems** [comment]
@jmuk 
I think you had some context on why the current design was implemented.

**Comment by garrettjonesgoogle** [comment]
This is an issue across all languages. We should probably aim for a solution that improves all languages instead of making Go unique.

**Comment by saicheems** [comment]
If the biggest issues is sharing the gRPC connection, we can get around that by adding a `ClientOption` where an existing connection can be provided.

Generating one client per API is trickier, toolkit is designed to generate on a service-by-service basis, so that change will take time and wider discussion as Garrett said.

**Comment by jba** [comment]
Maybe it's okay to generate one client per service. But could they all be
in the same package, since the protos are all in the same package?

That would require changing NewClient to New{Service}Client, but maybe not
much else.

For sharing connections, you'd need more than just the option because of
all the dialing smarts built in to the generated code. Maybe an exposed
Dial method, along with the option.

**Comment by broady** [comment]
Yes, I agree. If there are multiple services for an API, then `NewClient` should become `NewFooClient`.

I consider this to be a blocking issue for release. We came to a decision that the import paths for the generated clients should be `cloud.google.com/go/pubsub/apiv1` -- not to have packages in subpaths.

Apart from it making it difficult to discover the other relevant services for an API, it also makes any shared types/structs awkward to use. At the moment, they're imported directly from the generated proto code, but those types should eventually make it into the package itself.

**Comment by jmuk** [comment]
Originally the go clients for an API were in a same package, and then separated through the advices from @mcgreevy.

Also, I think this current style fits into the Go standard. Like explained https://blog.golang.org/package-names
> Since client code uses the package name as a prefix when referring to the package contents, the names for those contents need not repeat the package name. The HTTP server provided by the http package is called Server, not HTTPServer. Client code refers to this type as http.Server, so there is no ambiguity.

And similarly it's logging.Client (or metrics.Client), and that would be more concise.

What would be the benefit for putting them into the same package?

**Comment by broady** [comment]
I agree, the currently style is idiomatic, but spreads the client surface for an API across too many packages.

> Apart from it making it difficult to discover the other relevant services for an API, it also makes any shared types/structs awkward to use. At the moment, they're imported directly from the generated proto code, but those types should eventually make it into the package itself.

**Comment by jba** [comment]
> What would be the benefit for putting them into the same package?

1. It would match the proto package definition.
2. It will ease the burden on users. The HTTP surface doesn't make service-level distinctions at all. The gRPC one does distinguish services, but there is no reason to distinguish anything else.
3. It will improve the import paths. We would have ".../logging/apiv2", with package logging. Now we have ".../logging/apiv2/{logging,config,metrics}".

**Comment by jmuk** [comment]
Hm, I am not against this redesign if we have the clear benefit.  3 looks a clear benefit to me. I'll defer to Sai for the actual decision -- I'm putting the background information.

By the way, we do have a challenge for the naming of the client type -- similar to the sub-package names.
To repeat the context, sometimes the service names are quite redundant -- for example, each of the logging services are LoggingServiceV2/ConfigServiceV2/MetricsServiceV2. And logging/apiv2/LoggingServiceV2Client doesn't look concise and Go programmers might hate this.

So, possibly
- we might want to keep the existing sub-package-naming strategy to shorten those client names -- so they are MetricsClient / ConfigClient instead of MetricsServiceV2Client / ConfigServiceV2Client
- (optional -- not 100% sure) skip the client-prefix if the client name is same as the API name. So it's not LoggingClient, but logging/apiv2/Client for the logging service.

Thoughts?

**Comment by broady** [comment]
`logging.NewClient` alongside `logging.NewMetricsClient` and `logging.NewConfigClient` seems good to me.

**Comment by jba** [comment]
Let's just do logging.NewLoggingClient, or whatever the algorithm gives. It's
important to remember that the exact names don't matter for this API, since
it will be wrapped. So just do whatever is most straightforward. What is
important is that we have a single package.

Hopefully other APIs will do this better. If they don't, that will be the
time to add configurable client names. No need to take time on that now.

**Comment by saicheems** [comment]
One possible trick is to match the package name against the service name, and if they match (in the case of `logging` and `LoggingClient`) omit the prefix from client. May or may not be more trouble than it's worth, but it's an option.

**Comment by saicheems** [comment]
So I have a 95% working solution - the last bit is figuring out where to put the shared vars and consts.

There's a `gapicNameVersion` const and the `Done` error var that all the clients share. Is there a convention for a common go file where I can put this stuff? It's a little difficult to only generate them in 1 service client and not all 3, because of the way the generator is set up.

Maybe a `common.go`?

**Comment by jmuk** [comment]
We actually have `doc.go` file already, IIRC.  That was intended to have the API-wise doc comment but good for the place of saving common values. You'll see this pattern at https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/bigtable/doc.go for example.

`common.go` would work well, but in that case we should remove `doc.go`.

**Comment by saicheems** [comment]
Oh ok I didn't know there was convention to keep anything in `doc.go`

Would it be an issue to store path template functions and vars in there as well?

**Comment by jba** [comment]
I don't think we want anything but a comment and a package decl in doc.go. I'd prefer common.go.

@mcgreevy, @okdave, what do you think?

**Comment by mcgreevy** [comment]
I'm don't think it's particularly common to put non-comments in doc.go.  I would normally put this kind of stuff in <packagename>.go, but if that's difficult to achieve with the generator, than common.go should be fine.

**Comment by jba** [comment]
> I would normally put this kind of stuff in .go

Did you omit a filename there?

**Comment by mcgreevy** [comment]
I meant `<packagename>.go`, but it looks like github stripped out the part that looked like a tag.

**Comment by saicheems** [comment]
That's possible to do, I'll put the const and vars in `<packagename>.go`
