### ISSUE TITLE
Separate doc pipeline from GAPIC pipeline

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#239]
For languages that generate "doc" files (i.e., Python, Ruby), there should be separate pipelines for generating documentation and generating packages. The GAPIC pipeline should not produce the doc files.

cc: @jmuk @bjwatson

**Comment by jmuk** [comment]
Why?  Are there any problems of generating those files?

**Comment by geigerj** [comment]
No; the issue is more that if we want to generate a package for, e.g., PyPI, we do not want the doc files to shadow the modules generated by the gRPC pipeline. The code is not runnable out of the box with the doc files. In Python, they also confuse packman, which adds namespace packages in setup.py for the doc files that need to be removed manually when publishing the package.

**Comment by jmuk** [comment]
I see.

Actually that's not the case of Ruby -- they are placed on an unusual place and does not prevent gRPC clients, and without them, they won't be in the docsite (because the docsite simply generates the documentation from the rubygems file). But it's actually a bit related to https://github.com/googleapis/toolkit/issues/143 probably -- on Ruby, it's still confusing to users so I'm thinking to change the format of those doc files.

Anyways, I'm okay with separating those generation pipelines -- it's easy to run both for Ruby.
