### ISSUE TITLE
Rename "createWithDefaults" to "create" in Java

### ISSUE THREAD

**Issue by omaray** [googleapis/toolkit#248]
In java, when we instantiate a client object stub, the current static method is called createWithDefaults. 

EXPECTED RESULT
The static method should probably be called "create" since it's what we do in .NET and it's simpler and clearer.

IMPACT
Nice looking code. And consistent code across our languages.

**Comment by pongad** [comment]
@garrettjonesgoogle How close are we to finalizing the Java surface? Is this a change we can accommodate at all? I mean, the change isn't hard, but we most likely don't want to break anyone depending on us.

**Comment by garrettjonesgoogle** [comment]
Yes we can accommodate it because we are still in alpha externally. Our only consumer (gcloud-java) would just have a couple lines that need to be changed.

There is one reason to hold off for a tiny bit - we don't want to make changes to the Java surface until the MVVM refactoring for Java is merged, at least for non-urgent changes.

**Comment by garrettjonesgoogle** [comment]
This has been done for a while.
