### ISSUE TITLE
If a language snippet for a given method fails, have discoGen generate an empty file.

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/toolkit#291]
Having an empty rather than non-existent snippet in a fragment file eases the handling in other parts of our process.

**Comment by saicheems** [comment]
It's moderately tricky to change the generator to output empty files because the filename is generated so deep in the hierarchy (in each of the language's snippet files). If an error is encountered, it propagates all the way up and the whole generator fails.

This could be implemented as soon in the process as `CommonDiscoveryProvider.java` by amending the `generate` method, but the filename itself is retrieved from the result of the `generator.generate` call (btw, chasing all of the generate functions down the tree is frustrating...).

I'm assuming the reason for this change is that later stages don't know what files were supposed to be generated?
