### ISSUE TITLE
Consider looking for common acronyms in Go

### ISSUE THREAD

**Issue by saicheems** [googleapis/toolkit#422]
`Id` -> `ID`
`Http` -> `HTTP`

etc.

**Comment by jba** [comment]
+1

**Comment by saicheems** [comment]
Going through old bugs, Michael does this seem like something worth doing anywhere? I don't think there's much reason to do it in discovery, but maybe in toolkit?

Feel free to close if not.

**Comment by jba** [comment]
@pongad I do think this is valuable and should be easy (?). And we must do it before we release.

**Comment by pongad** [comment]
If I remember right, there might already be a support in toolkit for this. I'll investigate.

**Comment by pongad** [comment]
I have thought about this a little more. I think we shouldn't do this in gapic. It's been a while since I last worked on Discovery. It might be useful there; I'm not sure.

My reasoning is that doing this will make us consistent with Go style guide but inconsistent with generated protobuf code. For Pubsub, the [`message_id`](https://github.com/googleapis/googleapis/blob/9bab31c7a52dc33a5301cfa50b9d0515529a39f6/google/pubsub/v1/pubsub.proto#L225) field is generated into [`MessageId`](https://github.com/google/go-genproto/blob/de9f5e90fe9b278809363f08c2072d2f2a429de7/googleapis/pubsub/v1/pubsub.pb.go#L106).

Since Go asks directly for the protobuf message with no flattening, users will be writing the field name themselves. We'll essentially be forcing users to mix `Id` and `ID` in the same statement.

@saicheems @jba please let me know what you think.
