### ISSUE TITLE
Go codegen fails on non struct page streaming types

### ISSUE THREAD

**Issue by saicheems** [googleapis/toolkit#44]
Problem
======
If some page streaming function iterates on a resource field that is not a Message, the code generator fails unexpectedly. This is because the generator assumes incorrectly that all resource fields are Messages and cannot be primitive types.

Since the current solution is designed around struct types, slight renaming and modification is required.

Proposal
=======
-> Instead of using the Message type name as the prefix in the page streaming constructs, use the method's name: `ShelfPage -> ListShelvesPage`
-> Replace all struct references with primitive references if the resource field is a primitive.

**Comment by saicheems** [comment]
@vchudnov-g 
@pongad

**Comment by jmuk** [comment]
This current design came up through the discussion between me and gcloud-golang team, and I'm still thinking it's a good idea to name the stream by element type (like `ShelfIterator`) rather than the method name (like `ListShelvesIterator`). That is clearer and easier to understand (if Go had parametric types, that would be the best though...).

Why not simply capitalizing / falling back to a valid symbol for primitive types?  I mean, if the type is string, use `StringIterator` or `StringPage` for the type names, which would be good enough.

**Comment by saicheems** [comment]
Okay, seems reasonable. I wasn't sure if `StringPage` or `StringIterator` were too generic before, but now that I look at it, I think it's fine.

Will implement as you suggested.

**Comment by jmuk** [comment]
Note that any types in Go is scoped in the package. Indeed `StringIterator` sounds too generic, but at least it wouldn't break other packages.

**Comment by pongad** [comment]
Out of curiosity, has Go team signed off on our general iterator design? There seems to be a few design questions about it in Java and C#.

**Comment by jmuk** [comment]
I am not sure if some sign-off process exists, but this design at least addresses all of the feedback from gocloud team.
