### ISSUE TITLE
Don't use markdown in VKit comments

### ISSUE THREAD

**Issue by pongad** [googleapis/toolkit#475]
Comments like 
```
the `x-goog-api-client` header
```

should have the backticks removed.

**Comment by bjwatson** [comment]
Related PRs for Python:
- https://github.com/googleapis/toolkit/issues/222
- https://github.com/googleapis/toolkit/issues/402

**Comment by geigerj** [comment]
See also 
https://github.com/googleapis/toolkit/blob/master/src/main/java/com/google/api/codegen/CommentPatterns.java

and 

https://github.com/googleapis/toolkit/blob/master/src/main/java/com/google/api/codegen/py/PythonSphinxCommentFixer.java

for what Python does here. As discussed offline it would eventually be good to get a proper Markdown processor hooked up to this, like what we have internally.

**Comment by bjwatson** [comment]
@pongad @garrettjonesgoogle This seems like a duplicate of https://github.com/googleapis/toolkit/issues/331. I like how 331 is phrased better, because I want to make use of the backticks as a hint for code formatting, rather than just removing them (which only makes sense if a language's doc system has zero support for code formatting).

Unless I'm missing something subtle, one of these should be closed.

**Comment by garrettjonesgoogle** [comment]
Yeah, probably close this one (475).

**Comment by pongad** [comment]
Duplicate of #331
