### ISSUE TITLE
Order of keyword args between versions can cause breakage.

### ISSUE THREAD

**Issue by dhermes** [googleapis/toolkit#526]
In Python, keyword args can also be passed as positional args. So in [`gapic-google-logging-v2` (0.9.3)](https://pypi.python.org/pypi/gapic-google-logging-v2/0.9.3), `LoggingServiceV2Api.list_log_entries` had the signature:

``` python
def list_log_entries(self,
                     project_ids,
                     filter_='',
                     order_by='',
                     page_size=0,
                     options=None):
```

but in [`gapic-google-logging-v2` (0.10.1)](https://pypi.python.org/pypi/gapic-google-logging-v2/0.10.1), it became:

``` python
def list_log_entries(self,
                     project_ids,
                     resource_names=None,
                     filter_='',
                     order_by='',
                     page_size=0,
                     options=None):
```

i.e. it grew `resource_names` in the middle. Hence when we [called](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/4395b35adfabac9084c67184c74070db017a8a35/logging/google/cloud/logging/_gax.py#L81-L82) via positional only

``` python
page_iter = self._gax_api.list_log_entries(
    projects, filter_, order_by, page_size, options)
```

that code broke on the upgrade from 0.9.x to 0.10.x.

---

This is somewhat fine, but if you wanted, you could force users to always use some arguments as keywords by using `*args, **kwargs` and then unpacking `args` according to a specified length needed for positional and then removing from `kwargs` to sanitize.

**Comment by geigerj** [comment]
@bjwatson and I discussed this, and our initial thought is that we'd rather not take such a strong definition of what constitutes a breaking change; that is, if code breaks because it calls keyword arguments as positional parameters, that's not our concern.

To support this would require either (1) moving the `options` parameter to always be the first argument, and ensuring new optional arguments always appear at the end of the parameter list, or (2) using `*args, **kwargs` as the signature for all functions as you suggested. We'd prefer not to do (1) for stylistic and pragmatic reasons, and (2) seems un-Pythonic.

Still open to more discussion before we settle, though. @jonparrott, do you have any thoughts on this?

**Comment by jonparrott** [comment]
Please don't use `*args, **kwargs` as the signature for all functions.

In general, I feel that the calling code should specify keyword arguments explicitly. If we were in a Python 3-only world, we could use [keyword only arguments](https://www.python.org/dev/peps/pep-3102/).

**Comment by geigerj** [comment]
I don't think we intend to change GAPIC in this area; we'll consider it the responsibility of the calling code to specify kwargs explicitly.

**Comment by jonparrott** [comment]
I think it's fair to expect callers to specify kwargs as kwargs and not let
args overflow into kwargs. In Python 3, you can actually do keyword-only
args.
