### ISSUE TITLE
Consider binding auth to service in Node.js discovery sample gen

### ISSUE THREAD

**Issue by tcoffee-google** [googleapis/toolkit#655]
Currently auth is provided as part of request, where it clutters assignment of request parameters. Eric Koleda points out that it could be instead bound to the service at creation time, as in some examples here: https://github.com/google/google-api-nodejs-client#authorizing-and-authenticating

@vchudnov-g @saicheems what do you think?

**Comment by vchudnov-g** [comment]
So it's just setting the `auth` field on the service rather than in the request? Interesting and cool. I don't know that it simplifies things terribly, though. Yes, we'd separate the actual relevant parts of the request from the auth, which would be slightly clearer. But we'd be introducing a (less-common? I don't know) way of authenticating. I think we'd want to let people know they can authenticate on the request too. (So if we do this, maybe have a comment to that effect?).

Is there also service-level auth in the client libraries for the other languages?

**Comment by saicheems** [comment]
I'm thinking we leave this as-is? If I'm not mistaken this should only affect OAuth2 samples. It would require a day or two of work at least as well.

**Comment by tcoffee-google** [comment]
I suggest also demoting to P3, the implied taxonomy being:
P1 ~ sample bug corrections (including consistency bugs)
P2 ~ sample functionality enhancements
P3 ~ sample style or tooling improvements
