### ISSUE TITLE
Check all languages for cases where `pageToken` is in the request body

### ISSUE THREAD

**Issue by saicheems** [googleapis/toolkit#692]
Currently wrong in Node.js for `logging.entries.list`

Some APIs have the `pageToken` field in the request body. For a few languages we generate code as if it is in the parameter list instead. Only Go and Java are correct right now.

**Comment by saicheems** [comment]
Go is okay, Java is right.

**Comment by vchudnov-g** [comment]
Could you add a bit more context to this issue? ("Requests should ... but some do ... and so our samples do ..."). Nothing long, just a few words.

**Comment by saicheems** [comment]
Doen

**Comment by tcoffee-google** [comment]
Here is a summary of occurrences for 'pageToken' and 'nextPageToken' in recent live discovery docs:

Method parameters | Request body fields | Response fields | Methods
------------ | ------------- | ------------- | -------------
- | - | - | 3568
pageToken | - | nextPageToken | 663
- | pageToken | nextPageToken | cloudresourcemanager.organizations.search <br/> genomics.annotationSets.search <br/> genomics.annotations.search <br/> genomics.annotationsets.search <br/> genomics.callsets.search <br/> genomics.jobs.search <br/> genomics.readgroupsets.search <br/> genomics.reads.search <br/> genomics.references.search <br/> genomics.referencesets.search <br/> genomics.variants.search <br/> genomics.variantsets.search <br/> logging.entries.list <br/>
pageToken | - | - | adexchangebuyer.performanceReport.list <br/> books.layers.list <br/> calendar.acl.watch <br/> calendar.calendarList.watch <br/> calendar.events.watch <br/> calendar.settings.watch <br/> clouduseraccounts.linux.getLinuxAccountViews <br/> directory.users.watch <br/> drive.changes.watch <br/> ghire.feedbacks.list <br/> reports.activities.watch <br/> storage.objects.watchAll <br/>
- | - | nextPageToken | blogger.posts.search <br/> compute.projects.listXpnHosts <br/> sql.users.list <br/> urlshortener.url.list <br/> youtube.guideCategories.list <br/> youtube.videoCategories.list <br/>
pageToken | - | pageToken | bigquery.jobs.getQueryResults <br/> bigquery.tabledata.list <br/>
- | nextPageToken | nextPageToken | identitytoolkit.relyingparty.downloadAccount
- | - | pageToken | bigquery.jobs.query

**Comment by tcoffee-google** [comment]
To support current API implementations, we will use the following logic to determine whether a method supports page-streaming:

<pre>
LET a "page token name" be "pageToken" or "nextPageToken".
IF (
  the response has a field with a page token name AND (
    the method has a parameter with a page token name OR
    the request body has a field with a page token name) AND
  the method is not bigquery.tabledata.list)
THEN the method is page-streaming
ELSE the method is not page-streaming.
</pre>

The exception for bigquery.tabledata.list is necessary because bigquery.jobs.getQueryResults (a paging method) has an identical relevant signature, and they will not change their API.

**Comment by tcoffee-google** [comment]
@jba has [pointed out](https://github.com/google/google-api-go-client/issues/176#issuecomment-268683689) that, documentation notwithstanding, the response pageToken of bigquery.tabledata.list does function like a typical response nextPageToken, hence need not take exception. Thus https://github.com/googleapis/toolkit/issues/880 implements simplified logic:

<pre>
LET a "page token name" be "pageToken" or "nextPageToken".
IF (
  the response has a field with a page token name AND (
    the method has a parameter with a page token name OR
    the request body has a field with a page token name))
THEN the method is page-streaming
ELSE the method is not page-streaming.
</pre>

**Comment by tcoffee-google** [comment]
Fixed by:
https://github.com/googleapis/toolkit/pull/880
https://github.com/googleapis/toolkit/pull/989
https://github.com/googleapis/toolkit/pull/987
https://github.com/googleapis/toolkit/pull/986
https://github.com/google/google-api-ruby-client/pull/528
https://github.com/google/google-api-python-client/pull/330
https://github.com/google/google-api-go-client/commit/af8034156250c1b5b37af228eef7fe989e248b60
cl/146010256
