### ISSUE TITLE
Optional parameters with resource names can't be empty

### ISSUE THREAD

**Issue by jskeet** [googleapis/toolkit#834]
Example: `LoggingClient.WriteLogEntries` takes a `LogNameOneof`.

The parameter is optional in the API, but is in the generated code as a method parameter.

How do we "omit" it?

- If we pass in null, we'll get a NullReferenceException
- We can't create a resource name which is empty

I suspect we want to:

- Have an `EmptyResourceName` singleton
- Allow that as another "kind" in each oneof
- Parse "" to `EmptyResourceName.Instance`

// cc @michaelbausor who may run into the same thing for Java

**Comment by chrisdunelm** [comment]
Could we allow `null` in this case?

**Comment by jskeet** [comment]
I was wondering about that. Maybe. But we don't for string values... so if this is meant to be like the string property, it would be odd. We should probably only do *one* of those - I don't think we should have two ways of representing "an empty resource name".

**Comment by garrettjonesgoogle** [comment]
@michaelbausor and I were just discussing this yesterday! In my understanding, in proto3, native types can't be null, but objects (messages) can be. It's true that the underlying type is String (null), but the resource type is an object. I would probably go for making it null, and just translate between empty string and null resource type; I think that's a little simpler than an empty resource name class.

**Comment by michaelbausor** [comment]
Another reason I think to prefer null is to handle this when the resource name is not a oneof. So for example looking at [Group.parent_name in monitoring](https://github.com/googleapis/googleapis/blob/master/google/monitoring/v3/group.proto#L64), I think it is preferable to have group.getParentNameAsGroupName() return null, rather than have group.getParentNameAsGroupNameOneof() return a GroupNameOneof that supports a single valid format (GroupName) and the EmptyResourceName.

**Comment by chrisdunelm** [comment]
@michaelbausor, @garrettjonesgoogle C# implements this using `null`. If Java has also resolved this issue, then it can be closed.

**Comment by jskeet** [comment]
@garrettjonesgoogle Ping for closing?

**Comment by garrettjonesgoogle** [comment]
This is done in Java.
