### ISSUE TITLE
More idiomatic Go enums

### ISSUE THREAD

**Issue by jba** [googleapis/toolkit#98]
The proto compiler takes enums like

enum LogSeverity {
  DEFAULT = 0;
  DEBUG = 100;
  ..
}

and creates enum values with names LogSeverity_DEFAULT, LogSeverity_DEBUG, etc.

The toolkit should generate a more idiomatic enum in the client package, with constants named Default, Debug, etc. It should also generate the corresponding functions to convert to and from strings (just like the proto compiler does).

This feature could be off by default, but configurable per-enum when it was felt to be worth it. There would also need to be a way to tweak the names to avoid conflicts with the rest of the package.

**Comment by saicheems** [comment]
I'm a little hesitant on this feature - generally we've tried to avoid providing alternatives for proto generated code, even if it's more idiomatic. We ran into similar places where python could be improved, but decided against it. Enums are probably the simplest values to replace, but I think it would be odd to have the user refer to enums in the client rather than the proto packages, especially if we have to avoid naming conflicts.
